### ISSUE TITLE
pm2 install nethoncho/pm2-rrd fails

### ISSUE THREAD

**Issue by nethoncho** [nethoncho/pm2-rrd#1]
This is a new pm2 module project. I am getting the following errors while trying to install it.
```
$ pm2 install nethoncho/pm2-rrd
[PM2][Module] Installing module nethoncho/pm2-rrd
[PM2][Module] Module already installed. Updating.
[PM2][Module] Calling [NPM] to install nethoncho/pm2-rrd ...
+ @nethoncho/pm2-rrd@0.0.1
added 19 packages in 40.766s
[PM2][Module] Module downloaded
ENOENT: no such file or directory, open '/home/pi/.pm2/modules/pm2-rrd/node_modules/pm2-rrd/package.json'
module.js:538
    throw err;
    ^

Error: Cannot find module '/home/pi/.pm2/modules/pm2-rrd/node_modules/pm2-rrd/package.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at startModule (/usr/local/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:261:22)
    at /usr/local/lib/node_modules/pm2/lib/API/Modules/Modularizer.js:196:7
    at /usr/local/lib/node_modules/pm2/lib/Configuration.js:64:14
    at FSReqWrap.oncomplete (fs.js:135:15)
```

**Comment by nethoncho** [comment]
Fixed by 875d13783fb8af3650316d22e21aec6093f6b550875d13783fb8af3650316d22e21aec6093f6b550
